### ISSUE TITLE
Injecting app into components without creating new container class

### ISSUE THREAD

**Issue by taion** [martyjs/marty-lib#17]
If I want to use e.g. `this.app.userActions` in a component, I currently need to wrap the component in a `createContainer`. However, this instantiates a new container class, which seems somewhat wasteful.

It would be nice if we exposed some more lightweight method to wrap the component in such a way that only injects `app`, without creating a new React class.

**Comment by jhollingworth** [comment]
This is actually really easy to do. It's just refactoring [these lines](https://github.com/martyjs/marty-lib/blob/master/src/container/createContainer.js#L40-L46) into another function.

What's a sensible name for this function? `Marty.withApp(Component)`?

**Comment by taion** [comment]
I'd be happy with `withApp`. In this form I'd actually use it as a decorator, so it might be worth considering if you're happy with:

``` js
@withApp
class MyComponent extends React.Component {
  /* ... */
}
```

I think that looks pretty good.

**Comment by jhollingworth** [comment]
I really like the decorator! How about `component`? 

``` js
let { component } = require('marty');

@component
class MyComponent extends React.Component {
  /* ... */
}
```

**Comment by taion** [comment]
Either works. I think the downside of `@component` is that it would feel odd to use in the non-decorator form, while `withApp` would be okay in both.

**Comment by Deide** [comment]
Whatever it's called, when you just need to wrap the component, a decorator is much nicer. You could even use ES6 import syntax to rename it if you really wanted.

``` javascript
import React, {Component} from 'react';
import {container as fluxContainer} from 'marty';

@fluxContainer
class MyComponent extends Component {
    /* ... */
}
```

**Comment by taion** [comment]
Sure, but given that the syntax is going to be the same either way, and that decorators are still only an ES7 proposal, I think we should privilege the non-decorator form.

**Comment by taion** [comment]
I'm going to put together a PR with this as `@withApp` for now.

**Comment by taion** [comment]
On second thought, I'm going to go with `injectApp`.
